<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer Analytics Report</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            background: #f5f5f5;
            padding: 20px;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            padding: 40px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }

        .header {
            text-align: center;
            border-bottom: 3px solid #3b82f6;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }

        .header h1 {
            color: #1e40af;
            font-size: 28px;
            margin-bottom: 10px;
        }

        .header-info {
            display: flex;
            justify-content: space-between;
            margin-top: 15px;
            font-size: 14px;
            color: #666;
        }

        .header-info div {
            flex: 1;
        }

        .section {
            margin-bottom: 40px;
        }

        .section-title {
            background: #3b82f6;
            color: white;
            padding: 10px 15px;
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 15px;
            border-radius: 4px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        table thead {
            background: #f3f4f6;
        }

        table th {
            padding: 12px;
            text-align: left;
            font-weight: 600;
            color: #374151;
            border-bottom: 2px solid #e5e7eb;
        }

        table td {
            padding: 10px 12px;
            border-bottom: 1px solid #e5e7eb;
        }

        table tbody tr:hover {
            background: #f9fafb;
        }

        .stats-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }

        .stat-card {
            background: #f9fafb;
            padding: 20px;
            border-radius: 8px;
            border-left: 4px solid #3b82f6;
        }

        .stat-label {
            font-size: 12px;
            color: #6b7280;
            text-transform: uppercase;
            margin-bottom: 5px;
        }

        .stat-value {
            font-size: 24px;
            font-weight: bold;
            color: #1f2937;
        }

        .footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
            color: #9ca3af;
            font-size: 12px;
        }

        .no-data {
            text-align: center;
            padding: 40px;
            color: #9ca3af;
            font-style: italic;
        }

        @media print {
            body {
                background: white;
                padding: 0;
            }
            
            .container {
                box-shadow: none;
                padding: 20px;
            }

            .section {
                page-break-inside: avoid;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <!-- Header -->
        <div class="header">
            <h1>Customer Analytics Report</h1>
            <div class="header-info">
                <div><strong>Location:</strong> {{ $locationName }}</div>
                <div><strong>Date Range:</strong> {{ strtoupper($dateRange) }}</div>
                <div><strong>Generated:</strong> {{ $generatedAt }}</div>
            </div>
            <div style="margin-top: 10px; font-size: 13px; color: #666;">
                Generated by: {{ $generatedBy }}
            </div>
        </div>

        <!-- Customers Section -->
        @if(isset($data['customers']) && count($data['customers']) > 0)
        <div class="section">
            <div class="section-title">Customer List ({{ count($data['customers']) }} Total)</div>
            
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th style="text-align: center;">Bookings</th>
                        <th style="text-align: center;">Purchases</th>
                        <th style="text-align: right;">Total Spent</th>
                        <th>First Visit</th>
                        <th>Last Visit</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($data['customers'] as $customer)
                    <tr>
                        <td>{{ $customer['name'] }}</td>
                        <td>{{ $customer['email'] }}</td>
                        <td style="text-align: center;">{{ $customer['total_bookings'] }}</td>
                        <td style="text-align: center;">{{ $customer['total_purchases'] }}</td>
                        <td style="text-align: right;">${{ number_format($customer['total_spent'], 2) }}</td>
                        <td>{{ $customer['first_visit'] }}</td>
                        <td>{{ $customer['last_visit'] }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        @endif

        <!-- Revenue by Month Section -->
        @if(isset($data['revenue_by_month']) && count($data['revenue_by_month']) > 0)
        <div class="section">
            <div class="section-title">Revenue Trend (Last 9 Months)</div>
            
            <table>
                <thead>
                    <tr>
                        <th>Month</th>
                        <th style="text-align: right;">Bookings Revenue</th>
                        <th style="text-align: right;">Purchases Revenue</th>
                        <th style="text-align: right;">Total Revenue</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($data['revenue_by_month'] as $revenue)
                    <tr>
                        <td><strong>{{ $revenue['month'] }}</strong></td>
                        <td style="text-align: right;">${{ number_format($revenue['bookings_revenue'], 2) }}</td>
                        <td style="text-align: right;">${{ number_format($revenue['purchases_revenue'], 2) }}</td>
                        <td style="text-align: right;"><strong>${{ number_format($revenue['total_revenue'], 2) }}</strong></td>
                    </tr>
                    @endforeach
                    <tr style="background: #f3f4f6; font-weight: bold;">
                        <td>TOTAL</td>
                        <td style="text-align: right;">${{ number_format(collect($data['revenue_by_month'])->sum('bookings_revenue'), 2) }}</td>
                        <td style="text-align: right;">${{ number_format(collect($data['revenue_by_month'])->sum('purchases_revenue'), 2) }}</td>
                        <td style="text-align: right;">${{ number_format(collect($data['revenue_by_month'])->sum('total_revenue'), 2) }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        @endif

        <!-- Top Customers Section -->
        @if(isset($data['top_customers']) && count($data['top_customers']) > 0)
        <div class="section">
            <div class="section-title">Top 20 Customers by Bookings</div>
            
            <table>
                <thead>
                    <tr>
                        <th>Rank</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th style="text-align: center;">Bookings</th>
                        <th style="text-align: right;">Total Spent</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($data['top_customers'] as $index => $customer)
                    <tr>
                        <td><strong>{{ $index + 1 }}</strong></td>
                        <td>{{ $customer['name'] }}</td>
                        <td>{{ $customer['email'] }}</td>
                        <td style="text-align: center;">{{ $customer['bookings'] }}</td>
                        <td style="text-align: right;">${{ number_format($customer['total_spent'], 2) }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        @endif

        <!-- Top Activities Section -->
        @if(isset($data['top_activities']) && count($data['top_activities']) > 0)
        <div class="section">
            <div class="section-title">Top 10 Activities by Purchases</div>
            
            <table>
                <thead>
                    <tr>
                        <th>Rank</th>
                        <th>Activity Name</th>
                        <th style="text-align: center;">Purchases</th>
                        <th style="text-align: right;">Revenue</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($data['top_activities'] as $index => $activity)
                    <tr>
                        <td><strong>{{ $index + 1 }}</strong></td>
                        <td>{{ $activity['activity'] }}</td>
                        <td style="text-align: center;">{{ $activity['purchases'] }}</td>
                        <td style="text-align: right;">${{ number_format($activity['revenue'], 2) }}</td>
                    </tr>
                    @endforeach
                    <tr style="background: #f3f4f6; font-weight: bold;">
                        <td colspan="2">TOTAL</td>
                        <td style="text-align: center;">{{ collect($data['top_activities'])->sum('purchases') }}</td>
                        <td style="text-align: right;">${{ number_format(collect($data['top_activities'])->sum('revenue'), 2) }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        @endif

        <!-- Top Packages Section -->
        @if(isset($data['top_packages']) && count($data['top_packages']) > 0)
        <div class="section">
            <div class="section-title">Top 10 Packages by Bookings</div>
            
            <table>
                <thead>
                    <tr>
                        <th>Rank</th>
                        <th>Package Name</th>
                        <th style="text-align: center;">Bookings</th>
                        <th style="text-align: right;">Revenue</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($data['top_packages'] as $index => $package)
                    <tr>
                        <td><strong>{{ $index + 1 }}</strong></td>
                        <td>{{ $package['package'] }}</td>
                        <td style="text-align: center;">{{ $package['bookings'] }}</td>
                        <td style="text-align: right;">${{ number_format($package['revenue'], 2) }}</td>
                    </tr>
                    @endforeach
                    <tr style="background: #f3f4f6; font-weight: bold;">
                        <td colspan="2">TOTAL</td>
                        <td style="text-align: center;">{{ collect($data['top_packages'])->sum('bookings') }}</td>
                        <td style="text-align: right;">${{ number_format(collect($data['top_packages'])->sum('revenue'), 2) }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        @endif

        <!-- Footer -->
        <div class="footer">
            <p>This is an automated report generated by ZapZone Management System</p>
            <p>For questions or concerns, please contact your system administrator</p>
        </div>
    </div>
</body>
</html>
